type MFAMethod = {
  name: string;
  factorType: string;
  description: string;
  strength: 'Very Weak' | 'Weak' | 'Moderate' | 'Very Strong' | 'Maximum';
  aalLevel: string; // NIST AAL level
  phishResistant: boolean;
  deviceBound: boolean | 'Partial' | 'Depends';
  highlighted?: boolean; // For electric blue glow
};

const methods: MFAMethod[] = [
  {
    name: 'Password',
    factorType: 'Knowledge',
    description: 'A secret word or phrase you create and remember.',
    strength: 'Very Weak',
    aalLevel: 'AAL1',
    phishResistant: false,
    deviceBound: false,
  },
  {
    name: 'Security Questions (KBA)',
    factorType: 'Knowledge',
    description: 'Personal questions like "What was your first pet?" that can often be guessed or found online.',
    strength: 'Very Weak',
    aalLevel: 'AAL1',
    phishResistant: false,
    deviceBound: false,
  },
  {
    name: 'Email OTP / Magic Link',
    factorType: 'Possession',
    description: 'A code or link sent to your email address.',
    strength: 'Weak',
    aalLevel: 'AAL1',
    phishResistant: false,
    deviceBound: false,
  },
  {
    name: 'SMS OTP',
    factorType: 'Possession',
    description: 'A code sent to your phone via text message.',
    strength: 'Weak',
    aalLevel: 'AAL1*',
    phishResistant: false,
    deviceBound: false,
  },
  {
    name: 'TOTP Authenticator',
    factorType: 'Possession',
    description: 'A 6-digit code that changes every 30 seconds, generated by an app like Google Authenticator.',
    strength: 'Moderate',
    aalLevel: 'AAL2',
    phishResistant: false,
    deviceBound: 'Depends',
  },
  {
    name: 'Push Notification',
    factorType: 'Possession',
    description: 'A notification on your device asking you to approve or deny a login. Can be vulnerable to accidental approvals.',
    strength: 'Moderate',
    aalLevel: 'AAL2*',
    phishResistant: false,
    deviceBound: true,
  },
  {
    name: 'Passkey (Platform)',
    factorType: 'Possession + Inherence',
    description: 'A secure credential stored on your device using biometrics (like Touch ID or Face ID). Can sync across your devices.',
    strength: 'Very Strong',
    aalLevel: 'AAL2/AAL3',
    phishResistant: true,
    deviceBound: true,
    highlighted: true,
  },
  {
    name: 'FIDO2 Hardware Security Key',
    factorType: 'Possession (+ Inherence optional)',
    description: 'A physical USB or NFC device you plug in or tap. May require a PIN or fingerprint.',
    strength: 'Maximum',
    aalLevel: 'AAL2/AAL3',
    phishResistant: true,
    deviceBound: true,
  },
];

const getStrengthColor = (strength: MFAMethod['strength']) => {
  switch (strength) {
    case 'Very Weak':
      return 'bg-red-500';
    case 'Weak':
      return 'bg-orange-500';
    case 'Moderate':
      return 'bg-yellow-500';
    case 'Very Strong':
      return 'bg-cyan-500';
    case 'Maximum':
      return 'bg-[#00D9FF]';
    default:
      return 'bg-gray-500';
  }
};

const getStrengthWidth = (strength: MFAMethod['strength']) => {
  switch (strength) {
    case 'Very Weak':
      return 'w-1/5';
    case 'Weak':
      return 'w-2/5';
    case 'Moderate':
      return 'w-3/5';
    case 'Very Strong':
      return 'w-4/5';
    case 'Maximum':
      return 'w-full';
    default:
      return 'w-1/2';
  }
};

export default function MFALeaderboard() {
  return (
    <section className="py-24 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-4xl sm:text-5xl font-bold mb-4">
            How Do Passkeys Compare?
          </h2>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto mb-8">
            There are lots of ways to secure your accounts. Here's how passkeys stack up against other methods you might be familiar with.
          </p>
          <div className="max-w-4xl mx-auto bg-gray-900/50 rounded-xl p-6 border border-gray-800 mb-8">
            <p className="text-gray-300 text-lg leading-relaxed">
              <span className="font-semibold text-white">Quick answer:</span> Passkeys are the most secure and easiest to use. They can't be tricked by fake websites, and you don't have to remember anything or wait for text messages.
            </p>
          </div>
        </div>

        {/* Glassmorphism Table Container */}
        <div className="relative">
          <div className="backdrop-blur-xl bg-gray-900/40 rounded-2xl border border-gray-800/50 overflow-hidden shadow-2xl">
            {/* Responsive Table Wrapper */}
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-800/50">
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300 uppercase tracking-wider">
                      Method
                    </th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300 uppercase tracking-wider">
                      Type
                      <span className="block text-xs font-normal normal-case text-gray-400 mt-1">What you use to prove it's you</span>
                    </th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300 uppercase tracking-wider">
                      How It Works
                    </th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-300 uppercase tracking-wider">
                      How Secure?
                      <span className="block text-xs font-normal normal-case text-gray-400 mt-1">Based on security standards</span>
                    </th>
                    <th className="px-6 py-4 text-center text-sm font-semibold text-gray-300 uppercase tracking-wider">
                      Safe from Fake Websites?
                      <span className="block text-xs font-normal normal-case text-gray-400 mt-1">Phishing protection</span>
                    </th>
                    <th className="px-6 py-4 text-center text-sm font-semibold text-gray-300 uppercase tracking-wider">
                      Tied to Your Device?
                      <span className="block text-xs font-normal normal-case text-gray-400 mt-1">Device-bound</span>
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-800/30">
                  {methods.map((method, index) => (
                    <tr
                      key={index}
                      className={`transition-all hover:bg-gray-800/20 ${
                        method.highlighted
                          ? 'border-l-4 border-[#00D9FF] shadow-[0_0_20px_rgba(0,217,255,0.3)]'
                          : ''
                      }`}
                    >
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-white font-medium text-lg">
                          {method.name}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className="inline-flex items-center px-3 py-1.5 rounded-full text-sm font-medium bg-gray-800/50 text-gray-300 text-center">
                          {method.factorType}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="text-gray-400 text-base max-w-md">
                          {method.description}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex flex-col space-y-2 min-w-[200px]">
                          <div className="w-full bg-gray-800 rounded-full h-2.5 overflow-hidden">
                            <div
                              className={`h-full ${getStrengthColor(
                                method.strength
                              )} ${getStrengthWidth(method.strength)} transition-all`}
                            />
                          </div>
                          <div className="flex items-center space-x-2">
                            <span className="text-gray-300 text-sm font-medium">
                              {method.strength}
                            </span>
                            <span className="text-gray-400 text-xs">
                              ({method.aalLevel})
                            </span>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-center">
                        {method.phishResistant ? (
                          <div className="flex items-center justify-center group/tooltip relative">
                            <svg
                              className="w-6 h-6 text-green-500 cursor-help"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path
                                fillRule="evenodd"
                                d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                clipRule="evenodd"
                              />
                            </svg>
                            <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 hidden group-hover/tooltip:block w-max max-w-xs bg-gray-800 text-white text-sm font-medium rounded-lg p-2 border border-gray-600 shadow-2xl z-50">
                              Resistant to phishing attacks
                            </div>
                          </div>
                        ) : (
                          <div className="flex items-center justify-center group/tooltip relative">
                            <svg
                              className="w-6 h-6 text-red-500 cursor-help"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path
                                fillRule="evenodd"
                                d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                                clipRule="evenodd"
                              />
                            </svg>
                            <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 hidden group-hover/tooltip:block w-max max-w-xs bg-gray-800 text-white text-sm font-medium rounded-lg p-2 border border-gray-600 shadow-2xl z-50">
                              Vulnerable to phishing attacks
                            </div>
                          </div>
                        )}
                      </td>
                      <td className="px-6 py-4 text-center">
                        {method.deviceBound === true ? (
                          <div className="flex items-center justify-center group/tooltip relative">
                            <svg
                              className="w-6 h-6 text-green-500 cursor-help"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path
                                fillRule="evenodd"
                                d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                clipRule="evenodd"
                              />
                            </svg>
                            <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 hidden group-hover/tooltip:block w-max max-w-xs bg-gray-800 text-white text-sm font-medium rounded-lg p-2 border border-gray-600 shadow-2xl z-50">
                              Tied to your specific device
                            </div>
                          </div>
                        ) : method.deviceBound === 'Partial' ? (
                          <span className="text-yellow-400 text-sm font-medium cursor-help" title="Partially tied to device">Partial</span>
                        ) : method.deviceBound === 'Depends' ? (
                          <div className="flex items-center justify-center group/tooltip relative">
                            <svg
                              className="w-6 h-6 text-yellow-500 cursor-help"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path
                                fillRule="evenodd"
                                d="M10 18a8 8 0 100-16 8 8 0 000 16zM7 9a1 1 0 000 2h6a1 1 0 100-2H7z"
                                clipRule="evenodd"
                              />
                            </svg>
                            <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 hidden group-hover/tooltip:block w-max max-w-xs bg-gray-800 text-white text-sm font-medium rounded-lg p-2 border border-gray-600 shadow-2xl z-50">
                              Depends on implementation
                            </div>
                          </div>
                        ) : (
                          <div className="flex items-center justify-center group/tooltip relative">
                            <svg
                              className="w-6 h-6 text-red-500 cursor-help"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path
                                fillRule="evenodd"
                                d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                                clipRule="evenodd"
                              />
                            </svg>
                            <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 hidden group-hover/tooltip:block w-max max-w-xs bg-gray-800 text-white text-sm font-medium rounded-lg p-2 border border-gray-600 shadow-2xl z-50">
                              Not tied to your device
                            </div>
                          </div>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
}

